#!/usr/bin/python
import subprocess

tp_id = subprocess.check_output('xinput | grep TouchPad', shell=True).strip().split('\t')[1][3:]
is_on = subprocess.check_output('xinput --list-props ' + tp_id + ' | grep Enabled', shell=True).strip().split('\t')[1]
if is_on == '1':
	subprocess.call('xinput --set-prop ' + tp_id + ' "Device Enabled" 0', shell=True)
else:
	subprocess.call('xinput --set-prop ' + tp_id + ' "Device Enabled" 1', shell=True)
